### ISSUE TITLE
Support for Velocity

### ISSUE THREAD

**Issue by ghost** [YuFengyfca/KnapsackToGo2#1]
could you support for velocity?
[Velocity](https://velocitypowered.com/) is a brand new proxy, it's similar to Bungeecord

你能支持Velocity代理端吗?
[Velocity](https://velocitypowered.com/) 是一个全新的代理，类似于BC 

另外，再请求一个新功能：同步统计数据

**Comment by YuFengyfca** [comment]
插件同步数据不依靠代理端，只需要把插件放到子服的插件文件夹里，确保子服在同一台主机上，或使用MYSQL数据库。（就是放代理端里没鸟用🤗）
目前学业忙，还没有时间做同步统计数据，敬请谅解

**Comment by ghost** [comment]
> 插件同步数据不依靠代理端，只需要把插件放到子服的插件文件夹里，确保子服在同一台主机上，或使用MYSQL数据库。（就是放代理端里没鸟用🤗） 目前学业忙，还没有时间做同步统计数据，敬请谅解

好的谢谢（我就说怎么VC上模拟BC插件可以正常运行）
